### ISSUE TITLE
Supermarket

### ISSUE THREAD

**Issue by shortdudey123** [scoutapp/scout_cookbooks#32]
Doesn't look like this cookbook is on the supermarket.  Can it be added?

**Comment by composit** [comment]
Hey @shortdudey123 -

Thanks for pointing that out. We'll look into getting our cookbook up there.

**Comment by composit** [comment]
Sorry for the delay @shortdudey123 -

Cookbook is on the supermarket: https://supermarket.chef.io/cookbooks/scout

(a couple html formatting issues still to work out)

**Comment by shortdudey123** [comment]
Thanks!
