### ISSUE TITLE
Recommended replacement for node[:scout][:group]?

### ISSUE THREAD

**Issue by fancyremarker** [scoutapp/scout_cookbooks#39]
Hi all, it looks like support for `node[:scout][:group]` has been dropped in 83809b2. Is the recommended way to configure groups now

```ruby
group node[:scout][:group] do
  action :modify
  members 'scoutd'
  append true
end
```

Or something different? Thanks!

**Comment by composit** [comment]
@fancyremarker -

The installer automatically creates the scoutd group and adds the scout user. If you want to add the scoutd user to other groups, you can specify a `default[:scout][:groups]` array attribute (also just added this morning). Let me know if you have questions.

Matt

**Comment by fancyremarker** [comment]
Hey @composit, confirming that this worked. For instances on which Scout had already been installed, I needed to run `scoutctl restart` on the instance after running the default recipe.

**Comment by composit** [comment]
Ah. Thanks @fancyremarker . I added a restart to the group block, so that shouldn't be an issue in the future.
