### ISSUE TITLE
Duplicate servers created when using non-default `hostname` and `display_name`

### ISSUE THREAD

**Issue by fancyremarker** [scoutapp/scout_cookbooks#40]
We have several commonly named servers, and so we choose to identify them by their AWS instance ID (to guarantee uniqueness) and set their display name to something useful for human recognition in the UI. In other words:

```ruby
default[:scout][:hostname] = aws_instance_id
default[:scout][:display_name] = useful_diplay_name
```

At some point since 1c2547c, this introduced the undesired effect of first creating a server whose hostname and display_name were both default values, then creating a second server with our custom values. (With 1c2547c and prior revisions, only the 1 Scout server was created, as desired.)

The result is that we get 2 servers in Scout for every 1 instance we launch, and then we get noisy incidents when the first Scout server "isn't reporting." Any suggestions for how to fix this behavior?

**Comment by composit** [comment]
hey @fancyremarker -

Good timing! We've been testing out a fix for that issue this week and I just merged it. Give it a try and let me know if you have any issues/questions.

Cheers,

Matt

**Comment by fancyremarker** [comment]
Thanks @composit! Will test and report back.

**Comment by fancyremarker** [comment]
Hey @composit : Sorry for the delay in responding, but this also appears to be fixed in master. Thanks again!

**Comment by composit** [comment]
Great! Thanks for the feedback.
