### ISSUE TITLE
Please update chef supermarket with latest version(s)

### ISSUE THREAD

**Issue by leonardteo** [scoutapp/scout_cookbooks#49]
Hi guys!

Could you please update the Chef supermarket with the latest version? 0.4.2 fails to install on new Ubuntu 16 release because initctl is not found.

https://supermarket.chef.io/cookbooks/scout

Thank you!

**Comment by shortdudey123** [comment]
@dlanderson any updates on this?

**Comment by andre** [comment]
@leonardteo @shortdudey123 sorry for the delay! https://supermarket.chef.io/cookbooks/scout is updated. We'll do a better job of keeping this updated going forward.
